apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-claims-to-headers
plugin: request-transformer
config:
  add:
    headers:
      - "X-User-Id:{{jwt_claim_userId}}"
      - "X-User-Type:{{jwt_claim_type}}"
# Request Transformer plugin (to pull fields from JWT claims and inject them into headers)

# Works with the X-Credential-Claim-* headers that the JWT plugin sets.
# Example: if your JWT has { "userId": "123", "type": "admin" }, Kong will expose:
# X-Credential-Claim-userId: 123
# X-Credential-Claim-type: admin

# Then you use request-transformer to map those into simpler headers (e.g., X-User-Id, X-User-Type).
