apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-postgres-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/abhiram/Bootcamp/week-23-to-27/humane/backend/data/user-postgres #make sure the path exist
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi