# jwt-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
stringData:
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbm9uSWQiOiJlYjFjZjZkYi1jZWRjLTQ0YjctYmU2NS1iMzNiNjhiNDNjMDUiLCJjcmVhdGVkQXQiOjE3NDY5NTg2ODM3MjcsImV4cGlyZXNBdCI6MTc0NzA0NTA4MzcyNywicmV2b2tlZCI6ZmFsc2UsInR5cGUiOiJhbm9uIiwiaWF0IjoxNzQ2OTU4NjgzLCJleHAiOjE3NDY5NTk1ODN9.ws5E4o6Vx4rTHoOopcksxZe_OxZKxJaJBJ84UCj2Vlc" # Replace with your actual secret
---
# jwt-plugin.yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-auth
  namespace: default
plugin: jwt
config:
  key_claim_name: kid
  claims_to_verify: ["exp"]
  secret_is_base64: false
  run_on_preflight: false # we dont need to have this for preflight request
  # Remove the secretKeyRef and use direct reference
