# k8s/mongo-init.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
spec:
  template:
    spec:
      containers:
        - name: mongo-init
          image: mongo:7
          command:
            [
              "mongo",
              "--host",
              "mongo-0.mongo:27017",
              "--eval",
              "rs.initiate({_id: 'rs0', members: [{ _id: 0, host: 'mongo-0.mongo:27017' }, { _id: 1, host: 'mongo-1.mongo:27017' }, { _id: 2, host: 'mongo-2.mongo:27017' }]})",
            ]
      restartPolicy: OnFailure
