apiVersion: v1
kind: Secret
metadata:
  name: user-pod-secret
type: Opaque
stringData:
  NODE_ENV: "development"
  passwordSalt: "10"
  otpSalt: "5"
  otpTokenSecret: "031284428934a5da3f21d29ff35934eee070cbc90563beffcbeb5c84759c225c0e06b411bd2c286bd26b770de7a5b0aa80c57f713dbba5ed535f6c01e4e620db"
  resetPasswordTokenSecret: hellboyHowareyouisthisrandomenoughwellguessthisisnotsorryboys
  accessTokenSecret: "1ef930eac19b33cd5f48573822ea2949a1fdac781aca9e0ede49fb84d708fbf9941b7d60101490eeca2efb904ef8b92ac455105e1ce594e6085bc08107729e25"
  refreshTokenSecret: "57dbdcda537b4799dd2c956bb3c664e778494a6eec47c088055353596f5142d66af5dcd70ce0461f04ca344639177abd42fc6d45523df39a71f7006fc9ddc1e2"
  GOOGLE_CLIENT_ID: "359115787839-r6fp3m5l9hh0onhej06j7t7ac22qladc.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "465"
  SMTP_SERVICE: "gmail"
  SMTP_MAIL: arno.ar.dev@gmail.com
  SMTP_PASSWORD: pquzyoydorvellel
  KAFKAJS_NO_PARTITIONER_WARNING: "1" # get rid of kafkaks legacy support warning
  AWS_ACCESS_KEY: AKIA2AUOOTU5BFEXDJPG
  AWS_SECRET_KEY: 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
  AWS_REGION: ap-south-1
  AWS_S3_BUCKET_NAME: humane.social
  AWS_CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME: https://d4pllizvq43wd.cloudfront.net
  POSTGRES_URI: "postgresql://postgres:mysecretpassword@user-postgres-srv:5432/user-db"
