apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humane
      service: user
      type: web-server
  template:
    metadata:
      labels:
        app: humane
        service: user
        type: web-server
        service-name: user-srv # for logs service label - must match service.metadata.name
    spec:
      initContainers:
        - name: prisma-migrate
          image: abhiramar/userservice
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: user-pod-secret
      containers:
        - name: user-server
          image: abhiramar/userservice
          envFrom:
            - secretRef:
                name: user-pod-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
  labels:
    metrics: "true"
spec:
  selector:
    app: humane
    service: user
    type: web-server
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
