apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humane
      service: feed
      type: web-server
  template:
    metadata:
      labels:
        app: humane
        service: feed
        type: web-server
    spec:
      containers:
        - name: feed-server
          image: abhiramar/humane-feed-service
          envFrom:
            - secretRef:
                name: feed-pod-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: feed-srv
  labels:
    metrics: "true"
spec:
  selector:
    app: humane
    service: feed
    type: web-server
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
