apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humane
      service: email
      type: web-server
  template:
    metadata:
      labels:
        app: humane
        service: email
        type: web-server
        service-name: email-srv # for logs service label - must match service.metadata.name
    spec:
      containers:
        - name: email-server
          image: abhiramar/humane-email
          envFrom:
            - secretRef:
                name: email-pod-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: email-srv
  labels:
    metrics: "true"
spec:
  selector:
    app: humane
    service: email
    type: web-server
  ports: # might not need service for this usecase
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
