apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humane
      service: moderation
      type: web-server
  template:
    metadata:
      labels:
        app: humane
        service: moderation
        type: web-server
        service-name: moderation-srv # for logs service label - must match service.metadata.name
    spec:
      containers:
        - name: moderation-service
          image: abhiramar/humane-moderation-service
          envFrom:
            - secretRef:
                name: moderation-pod-secret
          resources:
            requests:
              memory: "1Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2.5"

---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
  labels:
    metrics: "true"
spec:
  selector:
    app: humane
    service: moderation
    type: web-server
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
