apiVersion: v1
kind: Service
metadata:
  name: user-postgres
spec:
  selector:
    app: user-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-postgres
spec:
  serviceName: user-postgres
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.5
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: user-postgres-secret
          volumeMounts:
            - name: user-postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1"
      volumes:
        - name: user-postgres-data
          persistentVolumeClaim:
            claimName: user-postgres-pvc
