const names = [
   'Liam',
   'Emma',
   'Noah',
   'Olivia',
   'Aiden',
   'Ava',
   'Elijah',
   'Sophia',
   'Lucas',
   'Isabella',
   'Mason',
   'Mia',
   'Logan',
   'Amelia',
   'James',
   'Harper',
   'Ethan',
   'Evelyn',
   'Jacob',
   'Abigail',
   'Michael',
   'Emily',
   'Benjamin',
   'Elizabeth',
   'Alexander',
   'Mila',
   'William',
   'Ella',
   'Daniel',
   'Avery',
   'Sebastian',
   'Sofia',
   'Matthew',
   'Camila',
   'Henry',
   'Aria',
   'Jackson',
   'Scarlett',
   'Levi',
   'Chloe',
   'Samuel',
   'Luna',
   'David',
   'Layla',
   'Joseph',
   'Riley',
   'Carter',
   'Zoey',
   'Owen',
   'Nora',
   'Wyatt',
   'Lily',
   'John',
   'Ellie',
   'Jack',
   'Grace',
   'Luke',
   'Hannah',
   'Jayden',
   'Aubrey',
   'Dylan',
   'Addison',
   'Grayson',
   'Stella',
   'Gabriel',
   'Natalie',
   'Isaac',
   'Zoe',
   'Lincoln',
   'Leah',
   'Anthony',
   'Hazel',
   'Julian',
   'Violet',
   'Andrew',
   'Aurora',
   'Joshua',
   'Savannah',
   'Christopher',
   'Penelope',
   'Theodore',
   'Audrey',
   'Caleb',
   'Brooklyn',
   'Ryan',
   'Bella',
   'Nathan',
   'Claire',
   'Thomas',
   'Skylar',
   'Christian',
   'Lucy',
   'Hunter',
   'Paisley',
   'Aaron',
   'Everly',
   'Eli',
   'Anna',
   'Adrian',
   'Caroline',
];

// variation in names
const spread = names.length; // max: names.length
export const demoUsers = Array.from({ length: 40 }, (_, i) => ({
   firstName: names[Math.floor(Math.random() * spread)],
   lastName: names[Math.floor(Math.random() * spread)],
   bio: `This is a bio for user ${i + 1}`,
   avatarKey: `avatars/user${i + 1}.jpg`,
   coverPhotoKey: `covers/user${i + 1}.jpg`,
   email: `${names[Math.floor(Math.random() * spread)]}-seed-${i + 1}@emai.com`,
   isBlocked: i % 7 === 0, // Every 7th user is blocked
   isHotUser: i % 3 === 0, // Every 3rd user is a hot user
}));
