apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-pod-config
data:
  NODE_ENV: "development"
  MONGODB_URI: mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/chat?replicaSet=rs0
  ELASTICSEARCH_PROXY_BASE_URL: http://elasticsearch-proxy-srv:3000
  AWS_CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME: https://d4pllizvq43wd.cloudfront.net
  KAFKAJS_NO_PARTITIONER_WARNING: "1" # get rid of kafkaks legacy support warning
