apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-pod-config
data:
  NODE_ENV: "development"
  KAFKAJS_NO_PARTITIONER_WARNING: "1" # get rid of kafkaks legacy support warning
  KAFKA_CLIENT_ID: humane-notificaion-srv
  KAFKA_BROKER_URI: kafka:9092
  MONGODB_URI: mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/notification?replicaSet=rs0
  ELASTICSEARCH_PROXY_BASE_URL: http://elasticsearch-proxy-srv:3000
