apiVersion: v1
kind: ConfigMap
metadata:
  name: writer-pod-config
data:
  NODE_ENV: "development"
  KAFKAJS_NO_PARTITIONER_WARNING: "1" # get rid of kafkaks legacy support warning
  ELASTICSEARCH_PROXY_BASE_URL: http://elasticsearch-proxy-srv:3000
  KAFKA_CLIENT_ID: humane-writer-srv
  KAFKA_BROKER_URI: kafka:9092
  MONGODB_URI: mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/writer?replicaSet=rs0
  AWS_REGION: ap-south-1
  AWS_S3_BUCKET_NAME: humane.social
  AWS_CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME: https://d4pllizvq43wd.cloudfront.net
