name: Build and Push Docker Images (Simple)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_USERNAME: your-dockerhub-username

jobs:
  build-services:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Build each service individually
    - name: Build and push chat-service
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-service:latest ./chat-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-service:latest
    
    - name: Build and push elasticsearch-proxy
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/elasticsearch-proxy:latest ./elasticsearch-proxy
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/elasticsearch-proxy:latest
    
    - name: Build and push email-service
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/email-service:latest ./email-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/email-service:latest
    
    - name: Build and push feed-service
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/feed-service:latest ./feed-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/feed-service:latest
    
    - name: Build and push moderation-service
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/moderation-service:latest ./moderation-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/moderation-service:latest
    
    - name: Build and push notification-service
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest ./notification-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest
    
    - name: Build and push reward-service
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reward-service:latest ./reward-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/reward-service:latest
    
    - name: Build and push user-service
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest ./user-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
    
    - name: Build and push writer-service
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/writer-service:latest ./writer-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/writer-service:latest