name: Force build all services

on:
   # runs only then job is dispatched via github actions UI
   workflow_dispatch:

jobs:
   build-services:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3

         - name: Log in to Docker Hub
           uses: docker/login-action@v3
           with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

         # Build each service individually with matching skaffold image names
         - name: Build and push chat-service
           run: |
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/humane-chat-service:latest ./chat-service
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/humane-chat-service:latest

         - name: Build and push elasticsearch-proxy
           run: |
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/humane-elasticsearch-proxy:latest ./elasticsearch-proxy
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/humane-elasticsearch-proxy:latest

         - name: Build and push email-service
           run: |
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/humane-email:latest ./email-service
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/humane-email:latest

         - name: Build and push feed-service
           run: |
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/humane-feed-service:latest ./feed-service
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/humane-feed-service:latest

         - name: Build and push moderation-service
           run: |
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/humane-moderation-service:latest ./moderation-service
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/humane-moderation-service:latest

         - name: Build and push notification-service
           run: |
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/humane-notification-service:latest ./notification-service
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/humane-notification-service:latest

         - name: Build and push reward-service
           run: |
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/humane-reward-service:latest ./reward-service
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/humane-reward-service:latest

         - name: Build and push user-service
           run: |
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/userservice:latest ./user-service
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/userservice:latest

         - name: Build and push writer-service
           run: |
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/humane-writer-service:latest ./writer-service
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/humane-writer-service:latest
